services:
  - type: web
    name: doc-to-pdf-converter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: UPLOAD_FOLDER
        value: uploads
      - key: CONVERTED_FOLDER
        value: converted
      - key: MAXIMUM_UPLOAD_FILE
        value: 3
      - key: PORT
        value: 10000 